SCALE_FACTOR: 0.8
N_CONV_BLOCKS: 5
CONV_RECEPTIVE_FIELD: 11

LEVEL:
  TYPE: "platform"
  NAME: "ex-4"

TRAIN:
  EPOCHS: 8000
  LR_SCHEDULER_STEPS: [3200, 5000]
  NOISE_UPDATE: 0.05

PATH:
  TRAIN:
    PROJECT_NAME: "ex-4"