# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_draw = QtWidgets.QWidget()
        self.tab_draw.setObjectName("tab_draw")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_draw)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.panel_left = QtWidgets.QWidget(self.tab_draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_left.sizePolicy().hasHeightForWidth())
        self.panel_left.setSizePolicy(sizePolicy)
        self.panel_left.setStyleSheet("#panel_left { border-right: 1px solid rgb(50, 65, 75); border-radius: 0px }")
        self.panel_left.setObjectName("panel_left")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.panel_left)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.panel_tilebox = QtWidgets.QScrollArea(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.panel_tilebox.sizePolicy().hasHeightForWidth())
        self.panel_tilebox.setSizePolicy(sizePolicy)
        self.panel_tilebox.setWidgetResizable(True)
        self.panel_tilebox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.panel_tilebox.setObjectName("panel_tilebox")
        self.panel_tilebox_scroll_area = QtWidgets.QWidget()
        self.panel_tilebox_scroll_area.setGeometry(QtCore.QRect(0, 0, 224, 408))
        self.panel_tilebox_scroll_area.setObjectName("panel_tilebox_scroll_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panel_tilebox_scroll_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panel_tilebox.setWidget(self.panel_tilebox_scroll_area)
        self.gridLayout_6.addWidget(self.panel_tilebox, 2, 0, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.combo_tileset = QtWidgets.QComboBox(self.widget_12)
        self.combo_tileset.setObjectName("combo_tileset")
        self.gridLayout_10.addWidget(self.combo_tileset, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_12, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.panel_left, 1, 1, 1, 1)
        self.panel_central = QtWidgets.QWidget(self.tab_draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.panel_central.sizePolicy().hasHeightForWidth())
        self.panel_central.setSizePolicy(sizePolicy)
        self.panel_central.setObjectName("panel_central")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.panel_central)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_13 = QtWidgets.QWidget(self.panel_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_7.addWidget(self.widget_11, 0, 3, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.edit_level_name = QtWidgets.QLineEdit(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_level_name.sizePolicy().hasHeightForWidth())
        self.edit_level_name.setSizePolicy(sizePolicy)
        self.edit_level_name.setObjectName("edit_level_name")
        self.gridLayout_8.addWidget(self.edit_level_name, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.widget_16, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBoxLevelRows = QtWidgets.QSpinBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxLevelRows.sizePolicy().hasHeightForWidth())
        self.spinBoxLevelRows.setSizePolicy(sizePolicy)
        self.spinBoxLevelRows.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxLevelRows.setMinimum(1)
        self.spinBoxLevelRows.setMaximum(1000)
        self.spinBoxLevelRows.setObjectName("spinBoxLevelRows")
        self.gridLayout_9.addWidget(self.spinBoxLevelRows, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 2, 1, 1)
        self.spinBoxLevelColumns = QtWidgets.QSpinBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxLevelColumns.sizePolicy().hasHeightForWidth())
        self.spinBoxLevelColumns.setSizePolicy(sizePolicy)
        self.spinBoxLevelColumns.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxLevelColumns.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxLevelColumns.setMinimum(1)
        self.spinBoxLevelColumns.setMaximum(1000)
        self.spinBoxLevelColumns.setObjectName("spinBoxLevelColumns")
        self.gridLayout_9.addWidget(self.spinBoxLevelColumns, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_7.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.widget_13, 0, 0, 1, 1)
        self.panel_grid = QtWidgets.QWidget(self.panel_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.panel_grid.sizePolicy().hasHeightForWidth())
        self.panel_grid.setSizePolicy(sizePolicy)
        self.panel_grid.setObjectName("panel_grid")
        self.gridLayout_12.addWidget(self.panel_grid, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.panel_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_13.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.button_clear = QtWidgets.QPushButton(self.widget_10)
        self.button_clear.setObjectName("button_clear")
        self.gridLayout_11.addWidget(self.button_clear, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_10, 0, 1, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_13.addWidget(self.widget_14, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.widget_4, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.panel_central, 1, 2, 1, 1)
        self.panel_bottom = QtWidgets.QWidget(self.tab_draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.panel_bottom.sizePolicy().hasHeightForWidth())
        self.panel_bottom.setSizePolicy(sizePolicy)
        self.panel_bottom.setStyleSheet("#panel_bottom { border-top: 1px solid rgb(50, 65, 75); border-radius: 0px }")
        self.panel_bottom.setObjectName("panel_bottom")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.panel_bottom)
        self.gridLayout_3.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.panel_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_3.addWidget(self.widget_8, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.panel_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 0, 4, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.panel_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_load_level = QtWidgets.QPushButton(self.widget_5)
        self.button_load_level.setObjectName("button_load_level")
        self.gridLayout_5.addWidget(self.button_load_level, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.panel_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_save = QtWidgets.QPushButton(self.widget_7)
        self.button_save.setObjectName("button_save")
        self.gridLayout_4.addWidget(self.button_save, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_7, 0, 2, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.panel_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_3.addWidget(self.widget_9, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.panel_bottom, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab_draw, "")
        self.tab_generate = QtWidgets.QWidget()
        self.tab_generate.setObjectName("tab_generate")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_generate)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.panel_generate_top = QtWidgets.QWidget(self.tab_generate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.panel_generate_top.sizePolicy().hasHeightForWidth())
        self.panel_generate_top.setSizePolicy(sizePolicy)
        self.panel_generate_top.setStyleSheet("#panel_generate_top { border-bottom: 1px solid rgb(50, 65, 75); border-radius: 0px }")
        self.panel_generate_top.setObjectName("panel_generate_top")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.panel_generate_top)
        self.gridLayout_19.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.widget_18 = QtWidgets.QWidget(self.panel_generate_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_19.addWidget(self.widget_18, 0, 2, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.panel_generate_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_5 = QtWidgets.QLabel(self.widget_17)
        self.label_5.setObjectName("label_5")
        self.gridLayout_20.addWidget(self.label_5, 0, 0, 1, 1)
        self.edit_project_name = QtWidgets.QLineEdit(self.widget_17)
        self.edit_project_name.setReadOnly(True)
        self.edit_project_name.setObjectName("edit_project_name")
        self.gridLayout_20.addWidget(self.edit_project_name, 0, 1, 1, 1)
        self.gridLayout_19.addWidget(self.widget_17, 0, 0, 1, 1)
        self.widget_25 = QtWidgets.QWidget(self.panel_generate_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget_25)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.button_load_project = QtWidgets.QPushButton(self.widget_25)
        self.button_load_project.setObjectName("button_load_project")
        self.gridLayout_21.addWidget(self.button_load_project, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.widget_25, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.panel_generate_top, 0, 0, 1, 1)
        self.panel_project = QtWidgets.QWidget(self.tab_generate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.panel_project.sizePolicy().hasHeightForWidth())
        self.panel_project.setSizePolicy(sizePolicy)
        self.panel_project.setObjectName("panel_project")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.panel_project)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.widget_15 = QtWidgets.QWidget(self.panel_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.widget_27 = QtWidgets.QWidget(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_27.sizePolicy().hasHeightForWidth())
        self.widget_27.setSizePolicy(sizePolicy)
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_23.addWidget(self.widget_27, 0, 0, 1, 1)
        self.widget_28 = QtWidgets.QWidget(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_28.sizePolicy().hasHeightForWidth())
        self.widget_28.setSizePolicy(sizePolicy)
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.widget_28)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_7 = QtWidgets.QLabel(self.widget_28)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_24.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_24.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_24.addWidget(self.spinBox_2, 0, 3, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_24.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_orig_level_size = QtWidgets.QLabel(self.widget_28)
        self.label_orig_level_size.setObjectName("label_orig_level_size")
        self.gridLayout_24.addWidget(self.label_orig_level_size, 0, 4, 1, 1)
        self.gridLayout_23.addWidget(self.widget_28, 0, 1, 1, 1)
        self.widget_29 = QtWidgets.QWidget(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_29.sizePolicy().hasHeightForWidth())
        self.widget_29.setSizePolicy(sizePolicy)
        self.widget_29.setObjectName("widget_29")
        self.gridLayout_23.addWidget(self.widget_29, 0, 2, 1, 1)
        self.gridLayout_22.addWidget(self.widget_15, 0, 0, 1, 1)
        self.panel_gen_level = QtWidgets.QWidget(self.panel_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.panel_gen_level.sizePolicy().hasHeightForWidth())
        self.panel_gen_level.setSizePolicy(sizePolicy)
        self.panel_gen_level.setObjectName("panel_gen_level")
        self.gridLayout_22.addWidget(self.panel_gen_level, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.panel_project, 1, 0, 1, 1)
        self.panel_generate_bottom = QtWidgets.QWidget(self.tab_generate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.panel_generate_bottom.sizePolicy().hasHeightForWidth())
        self.panel_generate_bottom.setSizePolicy(sizePolicy)
        self.panel_generate_bottom.setStyleSheet("#panel_generate_bottom { border-top: 1px solid rgb(50, 65, 75); border-radius: 0px }")
        self.panel_generate_bottom.setObjectName("panel_generate_bottom")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.panel_generate_bottom)
        self.gridLayout_16.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_23 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_16.addWidget(self.widget_23, 0, 5, 1, 1)
        self.widget_21 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_16.addWidget(self.widget_21, 0, 3, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_19)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.button_generate = QtWidgets.QPushButton(self.widget_19)
        self.button_generate.setObjectName("button_generate")
        self.gridLayout_17.addWidget(self.button_generate, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_19, 0, 2, 1, 1)
        self.widget_20 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_16.addWidget(self.widget_20, 0, 1, 1, 1)
        self.widget_22 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_16.addWidget(self.widget_22, 0, 0, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.panel_generate_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setObjectName("widget_24")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_24)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.button_save_generated = QtWidgets.QPushButton(self.widget_24)
        self.button_save_generated.setObjectName("button_save_generated")
        self.gridLayout_18.addWidget(self.button_save_generated, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_24, 0, 4, 1, 1)
        self.gridLayout_15.addWidget(self.panel_generate_bottom, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_generate, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Level Designer"))
        self.label.setText(_translate("MainWindow", "Tile Set"))
        self.label_4.setText(_translate("MainWindow", "Level Name:"))
        self.label_2.setText(_translate("MainWindow", "Level Size:"))
        self.label_3.setText(_translate("MainWindow", "x"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_load_level.setText(_translate("MainWindow", "Load Level"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_draw), _translate("MainWindow", "Draw Level"))
        self.label_5.setText(_translate("MainWindow", "Project:"))
        self.button_load_project.setText(_translate("MainWindow", "Load Project"))
        self.label_7.setText(_translate("MainWindow", "x"))
        self.label_6.setText(_translate("MainWindow", "Level Size:"))
        self.label_orig_level_size.setText(_translate("MainWindow", "(Original: - x -)"))
        self.button_generate.setText(_translate("MainWindow", "Generate"))
        self.button_save_generated.setText(_translate("MainWindow", "Save Level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_generate), _translate("MainWindow", "Generate Images"))
